Areas/Admin/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pantus.Models;
using Pantus.Utilities;
namespace Pantus.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MenusController : Controller
    {
        private readonly PantusContext _context;

        public MenusController(PantusContext context)
        {
            _context = context;
        }

        // GET: Admin/Menus
        public async Task<IActionResult> Index()
        {
            if (!Function.CanAccessAdminPage())
                return RedirectToAction("Index", "Login");
            return View(await _context.TbMenus.ToListAsync());
        }

        // GET: Admin/Menus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!Function.CanAccessAdminPage())
                return RedirectToAction("Index", "Login");
            if (id == null)
            {
                return NotFound();
            }

            var tbMenu = await _context.TbMenus
                .FirstOrDefaultAsync(m => m.MenuId == id);
            if (tbMenu == null)
            {
                return NotFound();
            }

            return View(tbMenu);
        }

        // GET: Admin/Menus/Create
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: Admin/Menus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MenuId,Title,Alias,Description,Levels,ParentId,Position,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy,IsActive,UrlPath")] TbMenu tbMenu)
        {
            if (!Function.CanAccessAdminPage())
                return RedirectToAction("Index", "Login");
            if (ModelState.IsValid)
            {
                tbMenu.Alias = Pantus.Utilities.Function.TitleSlugGenerationAlias(tbMenu.Title);
                _context.Add(tbMenu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tbMenu);
        }

        // GET: Admin/Menus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!Function.CanAccessAdminPage())
                return RedirectToAction("Index", "Login");
            if (id == null)
            {
                return NotFound();
            }

            var tbMenu = await _context.TbMenus.FindAsync(id);
            if (tbMenu == null)
            {
                return NotFound();
            }
            return View(tbMenu);
        }

        // POST: Admin/Menus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MenuId,Title,Alias,Description,Levels,ParentId,Position,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy,IsActive")] TbMenu tbMenu)
        {
            if (id != tbMenu.MenuId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbMenu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbMenuExists(tbMenu.MenuId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tbMenu);
        }

        // GET: Admin/Menus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
           
            if (id == null)
            {
                return NotFound();
            }

            var tbMenu = await _context.TbMenus
                .FirstOrDefaultAsync(m => m.MenuId == id);
            if (tbMenu == null)
            {
                return NotFound();
            }

            return View(tbMenu);
        }

        // POST: Admin/Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbMenu = await _context.TbMenus.FindAsync(id);
            if (tbMenu != null)
            {
                _context.TbMenus.Remove(tbMenu);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbMenuExists(int id)
        {
            return _context.TbMenus.Any(e => e.MenuId == id);
        }
    }
}

Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pantus.Models;
namespace Pantus.Controllers
{
    public class MenuController : Controller
    {
        private readonly PantusContext _context;
        public MenuController(PantusContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("/menu/{alias}-{id}.html")]
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null || _context.TbMenuItems == null)
            {
                return NotFound();
            }
            var menuItem = await _context.TbMenuItems.Include(i => i.Category).FirstOrDefaultAsync(m => m.MenuItemId == id);
            if (menuItem == null)
            {
                return NotFound();
            }
            ViewBag.menuid = id;
            ViewBag.MenuReview = _context.TbMenuReviews.Where(i => i.MenuItemId == id && i.IsActive).ToList();
            ViewBag.MenuRelated = _context.TbMenuItems.Where(i => i.MenuItemId != id && i.CategoryId == menuItem.CategoryId).Take(5).OrderByDescending(i => i.MenuItemId).ToList();
            ViewBag.MenuCategories = _context.TbMenuCategories.Where(i => i.CategoryId == menuItem.CategoryId && i.IsActive).ToList();

            return View(menuItem);
        }
         [HttpPost]
        public async Task<IActionResult> Create(int menuid, string name, int phone, int rating, string message)
        {
            try
            {
                // Kiểm tra xem blogId có hợp lệ không
                var menu = await _context.TbMenuItems.FirstOrDefaultAsync(b => b.MenuItemId == menuid);
                if (menu == null)
                {
                    return Json(new { status = false, message = "Menu không tồn tại." });
                }

                // Tạo đối tượng bình luận mới
                TbMenuReview contact = new TbMenuReview
                {
                    MenuItemId = menuid, 
                    Name = name,
                    Phone = phone,
                    Rating = rating,
                    Detail = message,
                    CreatedDate = DateTime.Now,
                    IsActive = true,
                    Image = "/assets/img/userreview/havi.jpg",
                };

                // Thêm vào cơ sở dữ liệu
                _context.Add(contact);
                await _context.SaveChangesAsync(); // Lưu thay đổi

                return Json(new { status = true });
            }
            catch
            {
                return Json(new { status = false });
            }
        }
    }
}

Areas/Admin/Views/Menus/Create.cshtml
@model Pantus.Models.TbMenu

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="text-center mb-4">
        <h1 class="mt-4 text-center text-primary" style="font-family: 'Playball', cursive; font-size: 36px;">Tạo Menu Mới</h1>
        <hr class="w-25 mx-auto" style="border-top: 3px solid orange;">
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <form asp-action="Create" class="p-4 border rounded shadow-sm" style="background-color: #fff8f0; border-color: orange;">
                <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

                <!-- Tiêu Đề -->
                <div class="form-group row">
                    <label asp-for="Title" class="col-sm-3 col-form-label text-danger">Tiêu Đề</label>
                    <div class="col-sm-9">
                        <input asp-for="Title" class="form-control" style="border-color: orange;" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>

                <!-- Alias -->
                <div class="form-group row">
                    <label asp-for="Alias" class="col-sm-3 col-form-label text-danger">Alias</label>
                    <div class="col-sm-9">
                        <input asp-for="Alias" class="form-control" style="border-color: orange;" />
                        <span asp-validation-for="Alias" class="text-danger"></span>
                    </div>
                </div>

                <!-- Mô Tả -->
                <div class="form-group row">
                    <label asp-for="Description" class="col-sm-3 col-form-label text-danger">Mô Tả</label>
                    <div class="col-sm-9">
                        <input asp-for="Description" class="form-control" style="border-color: orange;" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <!-- Mức -->
                <div class="form-group row">
                    <label asp-for="Levels" class="col-sm-3 col-form-label text-danger">Mức</label>
                    <div class="col-sm-9">
                        <input asp-for="Levels" class="form-control" style="border-color: orange;" />
                        <span asp-validation-for="Levels" class="text-danger"></span>
                    </div>
                </div>

                <!-- Menu Cha -->
                <div class="form-group row">
                    <label asp-for="ParentId" class="col-sm-3 col-form-label text-danger">Menu Cha</label>
                    <div class="col-sm-9">
                        <input asp-for="ParentId" class="form-control" style="border-color: orange;" />
                        <span asp-validation-for="ParentId" class="text-danger"></span>
                    </div>
                </div>
                <!-- Vị Trí -->
                <div class="form-group row">
                    <label asp-for="Position" class="col-sm-3 col-form-label text-danger">Vị Trí</label>
                    <div class="col-sm-9">
                        <input asp-for="Position" class="form-control" style="border-color: orange;" />
                        <span asp-validation-for="Position" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="UrlPath" class="col-sm-3 col-form-label text-danger">Mô Tả</label>
                    <div class="col-sm-9">
                        <input asp-for="UrlPath" class="form-control" style="border-color: orange;" />
                        <span asp-validation-for="UrlPath" class="text-danger"></span>
                    </div>
                </div>
                <!-- Hiển Thị -->
                <div class="form-group row">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-9 form-check">
                        <input class="form-check-input" asp-for="IsActive" style="border-color: orange;" />
                        <label asp-for="IsActive" class="form-check-label text-success">Hiển Thị</label>
                    </div>
                </div>

                <!-- Submit -->
                <div class="form-group row text-center">
                    <div class="col-sm-12">
                        <input type="submit" value="Tạo Mới" class="btn btn-outline-success px-4" />
                    </div>
                </div>
            </form>

            <div class="text-center mt-3">
                <a asp-action="Index" class="btn btn-outline-danger">Quay Lại Danh Sách</a>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Menus/Delete.cshtml
@model Pantus.Models.TbMenu

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="text-center mb-4">
        <h1 class="mt-4 text-center" style="font-family: 'Playball', cursive; font-size: 36px; color: #ff6600;">Xoá Menu Pantus</h1>
        <hr class="w-25 mx-auto" style="border-top: 3px solid #ff6600;">
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card p-5 shadow-lg" style="background-color: #f8f9fa; border: 1px solid #ced4da;">
                <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

                <form asp-action="Delete">
                    <div class="row mb-3">
                        <div class="col-4 text-end text-primary fw-bold">Tiêu Đề:</div>
                        <div class="col-8 text-success">@Html.DisplayFor(model => model.Title)</div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-4 text-end text-primary fw-bold">Alias:</div>
                        <div class="col-8 text-success">@Html.DisplayFor(model => model.Alias)</div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-4 text-end text-primary fw-bold">Mô Tả:</div>
                        <div class="col-8 text-success">@Html.DisplayFor(model => model.Description)</div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-4 text-end text-primary fw-bold">Mức:</div>
                        <div class="col-8 text-success">@Html.DisplayFor(model => model.Levels)</div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-4 text-end text-primary fw-bold">Menu Cha:</div>
                        <div class="col-8 text-success">@Html.DisplayFor(model => model.ParentId)</div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-4 text-end text-primary fw-bold">Hiện:</div>
                        <div class="col-8">@Html.DisplayFor(model => model.IsActive)</div>
                    </div>

                    <input type="hidden" asp-for="MenuId" />

                    <div class="text-center mt-4">
                        <button type="submit" class="btn btn-outline-danger px-4 me-2">Xoá</button>
                        <a asp-action="Index" class="btn btn-outline-warning px-4">Quay Lại Danh Sách</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Menus/Details.cshtml
@model Pantus.Models.TbMenu

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="text-center mb-4">
        <h2 class="text-primary" style="font-family: 'Playball', cursive; font-size: 36px;">Chi Tiết Menu Pantus</h2>
        <hr class="w-25 mx-auto" style="border-top: 3px solid orange;">
    </div>

    <div class="card shadow-sm">
        <div class="card-body">
            <h4 class="card-title text-center mb-4">Thông Tin Menu</h4>
            <dl class="row">
                <dt class="col-sm-4 font-weight-bold">Tiêu Đề:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.Title)</dd>

                <dt class="col-sm-4 font-weight-bold">Alias:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.Alias)</dd>

                <dt class="col-sm-4 font-weight-bold">Mô Tả:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.Description)</dd>

                <dt class="col-sm-4 font-weight-bold">Mức:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.Levels)</dd>

                <dt class="col-sm-4 font-weight-bold">Menu Cha:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.ParentId)</dd>

                <dt class="col-sm-4 font-weight-bold">Vị Trí:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.Position)</dd>

                <dt class="col-sm-4 font-weight-bold">Ngày Tạo:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.CreatedDate)</dd>

                <dt class="col-sm-4 font-weight-bold">Người Tạo:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.CreatedBy)</dd>

                <dt class="col-sm-4 font-weight-bold">Ngày Sửa:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.ModifiedDate)</dd>

                <dt class="col-sm-4 font-weight-bold">Người Sửa:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.ModifiedBy)</dd>

                <dt class="col-sm-4 font-weight-bold">Hiện:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.IsActive)</dd>
            </dl>
        </div>
    </div>

    <div class="text-center mt-4">
        <a asp-action="Edit" asp-route-id="@Model?.MenuId" class="btn btn-warning mr-2">Sửa</a>
        <a asp-action="Index" class="btn btn-secondary">Quay Lại Danh Sách</a>
    </div>
</div>

Areas/Admin/Views/Menus/Edit.cshtml
@model Pantus.Models.TbMenu

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="text-center mb-4">
        <h1 class="mt-4 text-center text-primary" style="font-family: 'Playball', cursive; font-size: 36px;">Sửa Menu Pantus</h1>
        <hr class="w-25 mx-auto" style="border-top: 3px solid orange;">
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <form asp-action="Edit" class="p-4 border rounded shadow-sm" style="background-color: #fff8f0; border-color: orange;">
                <input type="hidden" asp-for="MenuId" />
                <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

                <!-- Tiêu Đề -->
                <div class="form-group row">
                    <label asp-for="Title" class="col-sm-3 col-form-label">Tiêu Đề</label>
                    <div class="col-sm-9">
                        <input asp-for="Title" class="form-control" style="border-color: orange; color: red;" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>

                <!-- Alias -->
                <div class="form-group row">
                    <label asp-for="Alias" class="col-sm-3 col-form-label">Alias</label>
                    <div class="col-sm-9">
                        <input asp-for="Alias" class="form-control" style="border-color: orange; color: red;" />
                        <span asp-validation-for="Alias" class="text-danger"></span>
                    </div>
                </div>

                <!-- Mô Tả -->
                <div class="form-group row">
                    <label asp-for="Description" class="col-sm-3 col-form-label">Mô Tả</label>
                    <div class="col-sm-9">
                        <input asp-for="Description" class="form-control" style="border-color: orange; color: red;" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <!-- Mức -->
                <div class="form-group row">
                    <label asp-for="Levels" class="col-sm-3 col-form-label">Mức</label>
                    <div class="col-sm-9">
                        <input asp-for="Levels" class="form-control" style="border-color: orange; color: red;" />
                        <span asp-validation-for="Levels" class="text-danger"></span>
                    </div>
                </div>

                <!-- Menu Cha -->
                <div class="form-group row">
                    <label asp-for="ParentId" class="col-sm-3 col-form-label">Menu Cha</label>
                    <div class="col-sm-9">
                        <input asp-for="ParentId" class="form-control" style="border-color: orange; color: red;" />
                        <span asp-validation-for="ParentId" class="text-danger"></span>
                    </div>
                </div>

                <!-- Vị Trí -->
                <div class="form-group row">
                    <label asp-for="Position" class="col-sm-3 col-form-label">Vị Trí</label>
                    <div class="col-sm-9">
                        <input asp-for="Position" class="form-control" style="border-color: orange; color: red;" />
                        <span asp-validation-for="Position" class="text-danger"></span>
                    </div>
                </div>

                <!-- Hiển Thị -->
                <div class="form-group row">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-9 form-check">
                        <input class="form-check-input" asp-for="IsActive" style="border-color: orange;" />
                        <label asp-for="IsActive" class="form-check-label text-success">Hiển Thị</label>
                    </div>
                </div>

                <div class="form-group text-center">
                    <input type="submit" value="Lưu Lại" class="btn btn-outline-success px-4" />
                </div>
            </form>

            <div class="text-center mt-3">
                <a asp-action="Index" class="btn btn-outline-danger">Quay Lại Danh Sách</a>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Menus/Index.cshtml
@model IEnumerable<Pantus.Models.TbMenu>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1 class="mt-4 text-center text-primary" style="font-family: 'Playball', cursive; font-size: 36px;">Danh sách Menu</h1>

<p>
    <a type="button" asp-area="Admin" asp-controller="Menus" asp-action="Create" class="btn btn-primary mb-3">Thêm mới Menu</a>
</p>

<table class="table table-bordered table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">STT</th>
            <th scope="col">Tiêu Đề</th>
            <th scope="col">Alias</th>
            <th scope="col">Cấp</th>
            <th scope="col">Vị Trí</th>
            <th scope="col">Hiển Thị</th>
            <th scope="col" style="width: 150px;">Thao Tác</th>
        </tr>
    </thead>
    <tbody>
        @{
            int p = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>@(p++)</td>
                <td>@Html.DisplayFor(modelItem => item.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Alias)</td>
                <td>@Html.DisplayFor(modelItem => item.Levels)</td>
                <td>@Html.DisplayFor(modelItem => item.Position)</td>
                <td>
                    @if (item.IsActive)
                    {
                        <span class="badge badge-success text-success">Đang Hiển Thị</span>
                    }
                    else
                    {
                        <span class="badge badge-secondary text-danger">Không Hiển Thị</span>
                    }
                </td>
                <td>

                    <a asp-area="Admin" asp-controller="Menus" asp-action="Edit" asp-route-id="@item.MenuId" class="btn btn-sm btn-warning">Sửa</a>
                    <a asp-area="Admin" asp-controller="Menus" asp-action="Details" asp-route-id="@item.MenuId" class="btn btn-sm btn-info">Xem</a>
                    <a asp-area="Admin" asp-controller="Menus" asp-action="Delete" asp-route-id="@item.MenuId" class="btn btn-sm btn-danger"
                       onclick="return confirm('Bạn có chắc chắn muốn xóa mục này?');">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
</table>